import type { RouterMetaType } from "./routes.type";

const routerMeta: RouterMetaType = {
  HomePage: {
    name: "Home",
    path: "/",
    requiresLayout: true,
    feature: 'home',
    site: 'public',
    page: "HomePage",
    isAdmin: false,
  },
  LoginPage: {
    name: "Login",
    path: "/login",
    feature: 'auth',
    site: 'public',
    page: "LoginPage",
    requiresLayout: false,
    isAdmin: false,
  },
  RegisterPage: {
    name: "Register",
    path: "/register",
    feature: 'auth',
    site: 'public',
    page: "RegisterPage",
    requiresLayout: false,
    isAdmin: false,
  },
  DashboardPage: {
    name: "Dashboard",
    path: "/dashboard",
    feature: 'dashboard',
    site: 'private',
    page: "DashboardPage",
    requiresLayout: true,
    isAdmin: false,
  },
  DetailsPage: {
    name: "Details",
    path: "/products/:slug",
    feature: 'products',
    site: 'public',
    page: "DetailsPage",
    requiresLayout: true,
    isAdmin: false,
  },
  ListProductsPage: {
    name: "ListProduct",
    path: "/products",
    feature: 'products',
    site: 'public',
    page: "ListProductPage",
    requiresLayout: true,
    isAdmin: false,
  },
  ShoppingCartPage: {
    name: "Cart",
    path: "/cart",
    feature: 'cart',
    site: 'public',
    page: "ShoppingCartPage",
    requiresLayout: true,
    isAdmin: false,
  },
  WishlistPage: {
    name: "WishList",
    path: "/wishlist",
    feature: 'wishlist',
    site: 'public',
    page: "WishListPage",
    requiresLayout: true,
    isAdmin: false,
  },
  ContactPage: {
    name: "Contact",
    path: "/contact",
    feature: "contact",
    site: 'public',
    page: "ContactPage",
    requiresLayout: true,
    isAdmin: false,
  },
  FAQPage: {
    name: "FaQ",
    path: "/faq",
    feature: 'faq',
    site: 'public',
    page: "FAQPage",
    requiresLayout: true,
    isAdmin: false,
  },
  BlogNewsPage: {
    name: "BlogNews",
    path: "/blog",
    feature: 'blog',
    site: 'public',
    page: "BlogNewsPage",
    requiresLayout: true,
    isAdmin: false,
  },
  DashListProductPage: {
    name: "ListProduct",
    path: "/dashboard/products",
    feature: 'products',
    site: 'private',
    page: "DashListProductPage",
    requiresLayout: true,
    isAdmin: true,
  },
  DashCreateProductPage: {
    name: "CreateProduct",
    path: "/dashboard/products/create",
    feature: 'products',
    site: 'private',
    page: "DashCreateProductPage",
    requiresLayout: true,
    isAdmin: true,
  },
  DashEditProductPage: {
    name: "EditProduct",
    path: "/dashboard/products/:id/edit",
    feature: 'products',
    site: 'private',
    page: "DashEditProductPage",
    requiresLayout: true,
    isAdmin: true,
  },
  DashViewProductPage: {
    name: "ViewProduct",
    path: "/dashboard/products/:id",
    feature: 'products',
    site: 'private',
    page: "DashViewProductPage",
    requiresLayout: true,
    isAdmin: true,
  },
  DashListCategoryPage: {
    name: "ListCategory",
    path: "/dashboard/categories",
    feature: 'categories',
    site: 'private',
    page: "DashListCategoryPage",
    requiresLayout: true,
    isAdmin: true,
  },
  DashCreateCategoryPage: {
    name: "CreateCategory",
    path: "/dashboard/categories/create",
    feature: 'categories',
    site: 'private',
    page: "DashCreateCategoryPage",
    requiresLayout: true,
    isAdmin: true,
  },
  DashEditCategoryPage: {
    name: "EditCategory",
    path: "/dashboard/categories/:id/edit",
    feature: 'categories',
    site: 'private',
    page: "DashEditCategoryPage",
    requiresLayout: true,
    isAdmin: true,
  },
  DashViewCategoryPage: {
    name: "ViewCategory",
    path: "/dashboard/categories/:id",
    feature: 'categories',
    site: 'private',
    page: "DashViewCategoryPage",
    requiresLayout: true,
    isAdmin: true,
  },
  DashListUserPage: {
    name: "ListUser",
    path: "/dashboard/users",
    feature: 'auth',
    site: 'private',
    page: "DashListUserPage",
    requiresLayout: true,
    isAdmin: true,
  },
  DashCreateUserPage: {
    name: "CreateUser",
    path: "/dashboard/users/create",
    feature: 'auth',
    site: 'private',
    page: "DashCreateUserPage",
    requiresLayout: true,
    isAdmin: true,
  },
  DashEditUserPage: {
    name: "EditUser",
    path: "/dashboard/users/:id/edit",
    feature: 'auth',
    site: 'private',
    page: "DashEditUserPage",
    requiresLayout: true,
    isAdmin: true,
  },
  DashProfilePage: {
    name: "Profile",
    path: "/dashboard/profile",
    feature: 'profile',
    site: 'private',
    page: "DashProfilePage",
    requiresLayout: true,
    isAdmin: false,
  },
  DashOrderPage: {
    name: "Order",
    path: "/dashboard/orders",
    feature: 'orders',
    site: 'private',
    page: "DashOrderPage",
    requiresLayout: true,
    isAdmin: false,
  },
  DashListOrderPage: {
    name: "ListOrder",
    path: "/dashboard/allorders",
    feature: 'orders',
    site: 'private',
    page: "DashListOrderPage",
    requiresLayout: true,
    isAdmin: true,
  },
  DashPaymentConfirmationPage: {
    name: "PaymentConfirmation",
    path: "/dashboard/orders/confirmation",
    feature: 'orders',
    site: 'private',
    page: "DashPaymentConfirmationPage",
    requiresLayout: true,
    isAdmin: false,
  },
  DashPaymentPage: {
    name: "Payment",
    path: "/dashboard/payments",
    feature: 'payment',
    site: 'private',
    page: "DashPaymentPage",
    requiresLayout: true,
    isAdmin: false,
  },
  DashTrackPage: {
    name: "Track",
    path: "/tracking",
    feature: 'tracking',
    site: 'public',
    page: "DashTrackPage",
    requiresLayout: true,
    isAdmin: false,
  },
  DashTackTestPage: {
    name: "TrackTest",
    path: "/dashboard/tracktest",
    feature: 'tracking',
    site: 'private',
    page: "DashTackTestPage",
    requiresLayout: true,
    isAdmin: false,
  },
  DisplaySectionsManagerPage: {
    name: "DisplaySectionsManager",
    path: "/dashboard/display-sections",
    feature: 'showcase',
    site: 'private',
    page: "DisplaySectionsManagerPage",
    requiresLayout: true,
    isAdmin: true,
  },
  NotFoundPage: {
    name: "NotFound",
    path: "*",
    feature: 'notfound',
    site: 'public',
    page: "NotFoundPage",
    requiresLayout: false,
    isAdmin: false,
  },
};

export default routerMeta;
