import type { RouterMetaType } from "./routes.type";

const routerMeta: RouterMetaType = {
  HomePage: {
    name: "Home",
    path: "/",
    isShow: true,
    isCommon: true,
    requiresLayout: true,
    feature: 'home',
    page: "HomePage",
  },
  LoginPage: {
    name: "Login",
    path: "/login",
    isShow: true,
    isAuth: false,
    feature: 'auth',
    page: "LoginPage",
    requiresLayout: false,
  },
  RegisterPage: {
    name: "Register",
    path: "/register",
    isShow: true,
    isAuth: false,
    feature: 'auth',
    page: "RegisterPage",
    requiresLayout: false,
  },
  DashboardPage: {
    name: "Dashboard",
    path: "/dashboard",
    isShow: true,
    isAuth: false,
    feature: 'dashboard',
    page: "DashboardPage",
    requiresLayout: true,
  },
  DetailsPage: {
    name: "Details",
    path: "/product/:id",
    isShow: true,
    isAuth: false,
    feature: 'products',
    page: "DetailsPage",
    requiresLayout: true,
  },
  ListProductsPage: {
    name: "ListProduct",
    path: "/products",
    isShow: true,
    isAuth: false,
    feature: 'products',
    page: "ListProductPage",
    requiresLayout: true,
  },
  ShoppingCartPage: {
    name: "Cart",
    path: "/cart",
    isShow: true,
    isAuth: false,
    feature: 'cart',
    page: "ShoppingCartPage",
    requiresLayout: true,
  },
  WishlistPage: {
    name: "WishList",
    path: "/wishlist",
    isShow: true,
    isAuth: false,
    feature: 'cart',
    page: "WishListPage",
    requiresLayout: true,
  },
  ContactPage: {
    name: "Contact",
    path: "/contact",
    isShow: true,
    isAuth: false,
    feature: "contact",
    page: "ContactPage",
    requiresLayout: true,
  },
  FAQPage: {
    name: "FaQ",
    path: "/faq",
    isShow: true,
    isAuth: false,
    feature: 'faq',
    page: "FAQPage",
    requiresLayout: true,
  },
  BlogNewsPage: {
    name: "BlogNews",
    path: "/blog",
    isShow: true,
    isAuth: false,
    feature: 'blog',
    page: "BlogNewsPage",
    requiresLayout: true,
  }
};

export default routerMeta;
